#
# Build libpafe
#
name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install libusb
        run: sudo apt-get install libusb-1.0.0

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DLIBPAFE_BUILD_SAMPLES=ON

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
