#
# Build libpafe
#
name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        libusb_version: ['"libusb-0.1-*" libusb-dev', '"libusb-1.0-*"']

    steps:
      - uses: actions/checkout@v4

      - name: Install libusb
        run: sudo apt-get install ${{ matrix.libusb_version }}

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DLIBPAFE_BUILD_SAMPLES=ON

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
