name: Build on multi-platform

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install libusb from apt
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install "libusb-1.0-*"

      - name: Install libusb from brew
        if: startsWith(matrix.os, 'macos')
        run: brew install libusb

      - name: Install libusb from GitHub Release
        if: startsWith(matrix.os, 'windows')
        shell: bash
        run: |
          binaryURL=$(curl -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/libusb/libusb/releases/latest | jq -r '.assets[] | select(.browser_download_url | endswith("7z")) .browser_download_url')
          curl $binaryURL -o libusb-latest.7z
          7z x libusb-latest.7z -o libusb-latest
          rm libusb-latest.7z
          ls -R libusb-latest

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DLIBPAFE_BUILD_SAMPLES=ON -DLIBPAFE_BUILD_SHARED_LIBS=ON

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
